---
ACCESS_TOKEN_EXPIRES_IN: 1h
REFRESH_TOKEN_EXPIRES_IN: 7d
JWT_ACCESS_TOKEN_SECRET: "----- YOUR KEY -----"
JWT_REFRESH_TOKEN_SECRET: "----- YOUR KEY -----"
GOOGLE_MAPS_API_KEY: ""
SESSION_SECRETE_KEY: ""